apiVersion: v1
kind: PersistentVolume
metadata:
  name: static-pv
  labels:
    type: local
    app: django-static
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/static"