apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-pvc
  namespace: ping-web-ns
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: static-pv
