# Generated by Django 4.2.2 on 2023-10-20 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LineBotUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="使用者名稱"
                    ),
                ),
                (
                    "line_user_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=33,
                        unique=True,
                        verbose_name="使用者LineUserID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("0", "預設"), ("1", "註冊中")],
                        default="0",
                        max_length=1,
                        verbose_name="狀態",
                    ),
                ),
                ("bind_status", models.BooleanField(default=False, verbose_name="已綁定")),
                (
                    "pub_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="創建日期"),
                ),
                (
                    "last_updated_date",
                    models.DateTimeField(auto_now=True, verbose_name="最後更新日期"),
                ),
            ],
            options={
                "verbose_name": "Line帳號管理",
                "verbose_name_plural": "Line帳號管理",
            },
        ),
    ]
