apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: ping-web-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: nginx
          configMap:
            name: nginx-cm
        - name: static
          persistentVolumeClaim:
            claimName: static-pvc
      containers:
        - name: nginx
          image: nginx:1.25
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
              name: nginx
              readOnly: true
            - mountPath: "/data/static"
              name: static
