# Generated by Django 4.2.2 on 2023-10-16 05:20

from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img", models.ImageField(upload_to="about/", verbose_name="大頭照")),
                ("job_title", models.CharField(max_length=100, verbose_name="職稱")),
                ("is_active", models.BooleanField(default=False, verbose_name="啟用")),
            ],
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Article標題")),
                ("images", models.ImageField(upload_to="portfolio/")),
                ("url", models.URLField()),
                ("content", models.TextField(verbose_name="Article內容")),
                (
                    "create_dt",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                ("update_dt", models.DateTimeField(auto_now=True, verbose_name="更新時間")),
            ],
        ),
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("content", models.TextField()),
                ("date_published", models.DateTimeField(auto_now_add=True)),
                ("author", models.CharField(max_length=50)),
                ("tags", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=50, verbose_name="Education title"),
                ),
                ("content", mdeditor.fields.MDTextField()),
            ],
        ),
        migrations.CreateModel(
            name="EmailContactRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="寄件人")),
                ("email", models.EmailField(max_length=254, verbose_name="寄件人email")),
                ("subject", models.CharField(max_length=200, verbose_name="訊息主旨")),
                ("message", models.TextField(verbose_name="訊息內容")),
                ("log", models.TextField(verbose_name="收信log")),
                ("is_success", models.BooleanField(verbose_name="發送是否成功")),
                (
                    "date_received",
                    models.DateTimeField(auto_now_add=True, verbose_name="接收時間"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmailRecipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="收件人email")),
                ("is_active", models.BooleanField(verbose_name="啟用")),
            ],
        ),
        migrations.CreateModel(
            name="Introduce",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("about_introduce", models.TextField(verbose_name="About簡介")),
                ("about_introduce_job", models.TextField(verbose_name="About職業簡介")),
                (
                    "about_introduce_bottom",
                    models.TextField(verbose_name="Aboute最下方簡介"),
                ),
                ("skills_introduce", models.TextField(verbose_name="Skills簡介")),
                ("resume_introduce", models.TextField(verbose_name="Resume簡介")),
                ("portfolio_introduce", models.TextField(verbose_name="Portfolio簡介")),
                ("articles_introduce", models.TextField(verbose_name="Articles簡介")),
            ],
        ),
        migrations.CreateModel(
            name="PersonalInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "info",
                    models.CharField(max_length=50, unique=True, verbose_name="個資名稱"),
                ),
                ("value", models.CharField(max_length=50, verbose_name="個資值")),
                ("sort", models.PositiveIntegerField(default=0, verbose_name="顯示順序")),
                ("is_active", models.BooleanField(default=True, verbose_name="啟用")),
            ],
        ),
        migrations.CreateModel(
            name="PortfolioCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=255, verbose_name="類別")),
                (
                    "priority",
                    models.PositiveIntegerField(default=0, verbose_name="優先順序"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProfessionalExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=50, verbose_name="Professional Experience title"
                    ),
                ),
                ("content", mdeditor.fields.MDTextField()),
            ],
        ),
        migrations.CreateModel(
            name="Sumary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="Sumary title")),
                ("content", mdeditor.fields.MDTextField()),
            ],
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "skill_name",
                    models.CharField(max_length=100, unique=True, verbose_name="技能名稱"),
                ),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
                (
                    "parent",
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="person.skill",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("images", models.ImageField(upload_to="portfolio/")),
                ("alt_text", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=50, verbose_name="標題")),
                ("description", models.CharField(max_length=50, verbose_name="描述")),
                ("url", models.URLField(max_length=100, verbose_name="網址")),
                ("is_active", models.BooleanField(default=True, verbose_name="啟用")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="person.portfoliocategory",
                        verbose_name="類別",
                    ),
                ),
            ],
        ),
    ]
