# Generated by Django 3.2.14 on 2023-10-18 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_summary_delete_sumary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='title',
        ),
        migrations.AddField(
            model_name='skill',
            name='sort',
            field=models.PositiveIntegerField(default=0, verbose_name='顯示順序'),
        ),
    ]
